### ISSUE TITLE
Exception while migrating to Wildfly 14

### ISSUE THREAD

**Issue by sommermi** [emmartins/wildfly-server-migration#10] opened 2018-09-12 13:52 UTC
Hello I'm currently migrating from Wildfly 10.0.1 Final to Wildfly 14.0.0 Final and it seems your server migration tool does not recognize Wildfly 14. According to the latest changes this migration should be supported.

**Steps I did:**

1. download latest code base
2. `mvn clean install`
3. `unzip jboss-server-migration-1.3.0-SNAPSHOT.zip`
4.  Next i started the migration via ` ./jboss-server-migration.sh -s /home/msommer/Schreibtisch/WildflyUpdatePoc/wildfly-10.1.0.Final -t /home/msommer/Schreibtisch/WildflyUpdatePoc/wildfly-14.0.0.Final/`

**Results:**
Exception in console: 
`Retrieving servers...
 INFO  SOURCE server name: WildFly Full, version: 10.1.0.Final.
java.lang.IllegalArgumentException: WFCMTOOL000006: Failed to retrieve server TARGET, from base dir /home/msommer/Schreibtisch/WildflyUpdatePoc/wildfly-14.0.0.Final.
	at org.jboss.migration.core.ServerMigration.getServer(ServerMigration.java:186)
	at org.jboss.migration.core.ServerMigration.run(ServerMigration.java:134)
	at org.jboss.migration.cli.CommandLineServerMigration.main(CommandLineServerMigration.java:131)
`

Migrations log:
[migration.log](https://github.com/emmartins/wildfly-server-migration/files/2375408/migration.log)

I tested a migration from Wildfly 10.1.0.Final to Wildfly 13.0.0.Final this worked perfectly fine. 

Did I do something wrong or is this an error in the migration tool?

Best regards Michael

**Comment by kecksk0enig** [comment] 2018-09-12 13:57
ha, wanted to submit an issue to, but you where faster than me. Same issue
trying to migrate to 14.0.0 Final  or 14.0.1 Final

**Comment by kecksk0enig** [comment] 2018-09-12 14:11
I found a (possible solution)

add the missing entries in wildfly-server-migration/dist/standalone/pom.xml

currently there are no dependiencies for migration to wfly 14 in above mentioned file.

sinze those artifacts are build I tried adding       
<dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>jboss-server-migration-wildfly10.1-to-wildfly14.0</artifactId>
        </dependency>

in order to migrate my 10.1.0 instance to 14.0.1 Final.

now the issue is gone

**Comment by kecksk0enig** [comment] 2018-09-12 14:29
However I get another error on migrationn



``
2018-09-12 16:25:38,137 ERROR [logger] Migration failed: org.jboss.migration.core.ServerMigrationFailureException: java.lang.IllegalStateException: WFLYEMB0018: Cannot get reflective method 'create' for: org.wildfly.core.embedded.EmbeddedStandaloneServerFactory
        at org.jboss.migration.core.task.TaskExecutionImpl.run(TaskExecutionImpl.java:174) [jboss-server-migration-core-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
        at org.jboss.migration.core.task.TaskExecutionImpl.execute(TaskExecutionImpl.java:159) [jboss-server-migration-core-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
        at org.jboss.migration.core.task.TaskContextImpl.execute(TaskContextImpl.java:68) [jboss-server-migration-core-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
        at org.jboss.migration.core.task.TaskContextImpl.execute(TaskContextImpl.java:32) [jboss-server-migration-core-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
        at org.jboss.migration.wfly10.config.task.ServerConfigurationsMigration$Task.migrateConfig(ServerConfigurationsMigration.java:151) [jboss-server-migration-wildfly10.0-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
        at org.jboss.migration.wfly10.config.task.ServerConfigurationsMigration$Task.migrateAllConfigs(ServerConfigurationsMigration.java:120) [jboss-server-migration-wildfly10.0-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
        at org.jboss.migration.wfly10.config.task.ServerConfigurationsMigration$Task.run(ServerConfigurationsMigration.java:105) [jboss-server-migration-wildfly10.0-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
        at org.jboss.migration.core.task.TaskExecutionImpl.run(TaskExecutionImpl.java:169) [jboss-server-migration-core-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
        at org.jboss.migration.core.task.TaskExecutionImpl.execute(TaskExecutionImpl.java:159) [jboss-server-migration-core-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
        at org.jboss.migration.core.task.TaskContextImpl.execute(TaskContextImpl.java:68) [jboss-server-migration-core-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
        at org.jboss.migration.core.task.TaskContextImpl.execute(TaskContextImpl.java:32) [jboss-server-migration-core-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
        at org.jboss.migration.wfly10.config.task.StandaloneServerMigration$1.run(StandaloneServerMigration.java:61) [jboss-server-migration-wildfly10.0-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
        at org.jboss.migration.core.console.UserConfirmationServerMigrationTask.runTask(UserConfirmationServerMigrationTask.java:58) [jboss-server-migration-core-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
        at org.jboss.migration.core.console.UserConfirmationServerMigrationTask.confirmTaskRun(UserConfirmationServerMigrationTask.java:50) [jboss-server-migration-core-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
        at org.jboss.migration.core.console.UserConfirmationServerMigrationTask.run(UserConfirmationServerMigrationTask.java:63) [jboss-server-migration-core-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
        at org.jboss.migration.core.env.SkippableByEnvServerMigrationTask.run(SkippableByEnvServerMigrationTask.java:47) [jboss-server-migration-core-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
        at org.jboss.migration.core.task.TaskExecutionImpl.run(TaskExecutionImpl.java:169) [jboss-server-migration-core-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
        at org.jboss.migration.core.task.TaskExecutionImpl.execute(TaskExecutionImpl.java:159) [jboss-server-migration-core-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
        at org.jboss.migration.core.task.TaskContextImpl.execute(TaskContextImpl.java:68) [jboss-server-migration-core-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
        at org.jboss.migration.core.task.TaskContextImpl.execute(TaskContextImpl.java:32) [jboss-server-migration-core-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
        at org.jboss.migration.wfly10.config.task.ServerMigration.run(ServerMigration.java:45) [jboss-server-migration-wildfly10.0-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
        at org.jboss.migration.wfly10.WildFlyServer10.migrate(WildFlyServer10.java:40) [jboss-server-migration-wildfly10.0-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
        at org.jboss.migration.core.ServerMigration$1.run(ServerMigration.java:153) [jboss-server-migration-core-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
        at org.jboss.migration.core.task.TaskExecutionImpl.run(TaskExecutionImpl.java:169) [jboss-server-migration-core-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
        at org.jboss.migration.core.ServerMigration.run(ServerMigration.java:160) [jboss-server-migration-core-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
        at org.jboss.migration.cli.CommandLineServerMigration.main(CommandLineServerMigration.java:131) [jboss-server-migration-cli-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
Caused by: java.lang.IllegalStateException: WFLYEMB0018: Cannot get reflective method 'create' for: org.wildfly.core.embedded.EmbeddedStandaloneServerFactory
        at org.wildfly.core.embedded.EmbeddedProcessFactory.createStandaloneServer(EmbeddedProcessFactory.java:180) [wildfly-embedded-5.0.0.Final.jar:5.0.0.Final]
        at org.wildfly.core.embedded.EmbeddedProcessFactory.createStandaloneServer(EmbeddedProcessFactory.java:116) [wildfly-embedded-5.0.0.Final.jar:5.0.0.Final]
        at org.jboss.migration.wfly10.config.management.impl.EmbeddedStandaloneServerConfiguration.startConfiguration(EmbeddedStandaloneServerConfiguration.java:87) [jboss-server-migration-wildfly10.0-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
        at org.jboss.migration.wfly10.config.management.impl.AbstractManageableServerConfiguration.start(AbstractManageableServerConfiguration.java:70) [jboss-server-migration-wildfly10.0-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
        at org.jboss.migration.wfly10.config.task.ServerConfigurationMigration$1.run(ServerConfigurationMigration.java:96) [jboss-server-migration-wildfly10.0-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
        at org.jboss.migration.core.task.TaskExecutionImpl.run(TaskExecutionImpl.java:169) [jboss-server-migration-core-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
        ... 25 more
Caused by: java.lang.NoSuchMethodException: org.wildfly.core.embedded.EmbeddedStandaloneServerFactory.create(java.io.File, org.jboss.modules.ModuleLoader, java.util.Properties, java.util.Map, [Ljava.lang.String;)
        at java.lang.Class.getMethod(Class.java:1786) [rt.jar:1.8.0_181]
        at org.wildfly.core.embedded.EmbeddedProcessFactory.createStandaloneServer(EmbeddedProcessFactory.java:178) [wildfly-embedded-5.0.0.Final.jar:5.0.0.Final]
        ... 30 more
``

**Comment by emmartins** [comment] 2018-09-12 14:47
hi, thanks for the issue report, I went on vacation right after the wf14 related modules merge, and postponed testing for later since at that time there wf14 final was not yet released... Anyway, this is not the project issue tracker, I will look into this but please report at https://issues.jboss.org/projects/CMTOOL next time ;-)

**Comment by emmartins** [comment] 2018-09-12 14:48
I was made aware on changes at wildfly core's embedded server, somehow suspect your second issue is related to that.

**Comment by kecksk0enig** [comment] 2018-09-12 14:53
Thanks for the fast feedback, maybe put a link into the readme to correct bugtracker, and disable this one :) Happy afterholliday :)

**Comment by sommermi** [comment] 2018-09-12 16:09
Thanks for your fast feedback. Enjoy your holiday.

**Comment by emmartins** [comment] 2018-09-17 20:32
The 2 issues in the tool's JIRA:
* https://issues.jboss.org/browse/CMTOOL-218
* https://issues.jboss.org/browse/CMTOOL-219

Both issues, and 3rd one I found wrt WFLY 14, are now fixed at master. Please build and try it out, if any issue persists please reopen/create issue at JIRA.

**Closed by emmartins** 2018-09-17 20:32 UTC

**Comment by emmartins** [comment] 2018-09-17 20:37
Two more things:
- this is my personal repo not the tool's project's repo, which is wildfly/wildfly-server-migration , please fork and use that.
- I'm going to remove this issue tracker feature, not sure if this conversation will still be available after...
